name: Build and Upload Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write # 授予 GITHUB_TOKEN 写入发布资源的权限

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: web/src/package-lock.json

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26.3

      - name: Run build script
        run: ./build.sh

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**

      - name: Clean up dist directory
        run: rm -rf ./dist
